"""DateTime to Date in AVM model

Revision ID: 509e9623a619
Revises: 7e2025a12ea7
Create Date: 2024-01-20 00:46:52.692700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '509e9623a619'
down_revision = '7e2025a12ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AVM', schema=None) as batch_op:
        batch_op.alter_column('valuation_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AVM', schema=None) as batch_op:
        batch_op.alter_column('valuation_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
