"""update fields in AVM model

Revision ID: a3fc0794fe32
Revises: 509e9623a619
Create Date: 2024-01-20 02:04:45.101778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3fc0794fe32'
down_revision = '509e9623a619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AVM', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_price',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_area',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('price_m2',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AVM', schema=None) as batch_op:
        batch_op.alter_column('price_m2',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_area',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
